name: "Vendor Agreement"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  VAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "Vendor Agreement Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the Vendor Agreement and I hereby sign the Agreement') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: cla-assistant/github-action@v2.1.2-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/fonoster/marketplace/blob/main/vendor.md'
          # branch should not be protected
          branch: 'main'
          allowlist: bot*
